package output.pojo;

public class UserWithBLOBs extends User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.address
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.resume
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String resume;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.address
     *
     * @return the value of user.address
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.address
     *
     * @param address the value for user.address
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.resume
     *
     * @return the value of user.resume
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getResume() {
        return resume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.resume
     *
     * @param resume the value for user.resume
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setResume(String resume) {
        this.resume = resume == null ? null : resume.trim();
    }
}