package output.pojo;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.first_login_check
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private Integer firstLoginCheck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.nickname
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_changed
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private Byte isChanged;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.creation_date
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private Integer creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.modification_date
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private Integer modificationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.modification_user
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private Integer modificationUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sex
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private Byte sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.country
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.province
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.city
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.county
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mobile
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mobile_imei
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String mobileImei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mobile_type
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String mobileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.usercol
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String usercol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.card
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String card;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.utype
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private Byte utype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.hospital_id
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private Integer hospitalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.hospital
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String hospital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.department_id
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private Integer departmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.department
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.title
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private Integer title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.excel
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String excel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.scount
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private Byte scount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sn_number
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String snNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sdrst
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private Integer sdrst;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sdserst
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private Integer sdserst;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.last_time
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private Integer lastTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.last_ip
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String lastIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.img_url
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.telephone
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.last_update_time
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private Integer lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.last_blood_time
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private Integer lastBloodTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.birthday
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private Integer birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mobile1
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String mobile1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mobile2
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String mobile2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.pic_url
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String picUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.dept_pic_url
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String deptPicUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_share_doctor
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private Byte isShareDoctor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_share_community
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private Byte isShareCommunity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.token
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.im_status
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private Byte imStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.im_password
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String imPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.salt
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.union_id
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String unionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.nurse
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private Integer nurse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.card_no
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.card_name
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String cardName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.card_type
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private Byte cardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.card_bank
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String cardBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.status
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.code
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.doctor_voice
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String doctorVoice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.channel
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.license
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String license;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.wx_doctor
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private Integer wxDoctor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.wx_show
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private Byte wxShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.expireAt
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private Integer expireat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.deviceUUID
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String deviceuuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.os
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String os;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.osVer
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String osver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.appVer
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String appver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.card_mobile
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String cardMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.pttype
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private Byte pttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.active
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private Byte active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.referer
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String referer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.first_auth
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private Byte firstAuth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.trusteeshipStatus
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private Boolean trusteeshipstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.offline_channel_referer
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String offlineChannelReferer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.doctor_type
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private Byte doctorType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.coin
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private Integer coin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gmt_create
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gmt_modify
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private Date gmtModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.wechat_union_id
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String wechatUnionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.subscribe_open_id
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private String subscribeOpenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.subscribe_state
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    private Byte subscribeState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.first_login_check
     *
     * @return the value of user.first_login_check
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public Integer getFirstLoginCheck() {
        return firstLoginCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.first_login_check
     *
     * @param firstLoginCheck the value for user.first_login_check
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setFirstLoginCheck(Integer firstLoginCheck) {
        this.firstLoginCheck = firstLoginCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.nickname
     *
     * @return the value of user.nickname
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.nickname
     *
     * @param nickname the value for user.nickname
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_changed
     *
     * @return the value of user.is_changed
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public Byte getIsChanged() {
        return isChanged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_changed
     *
     * @param isChanged the value for user.is_changed
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setIsChanged(Byte isChanged) {
        this.isChanged = isChanged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.creation_date
     *
     * @return the value of user.creation_date
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public Integer getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.creation_date
     *
     * @param creationDate the value for user.creation_date
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setCreationDate(Integer creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.modification_date
     *
     * @return the value of user.modification_date
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public Integer getModificationDate() {
        return modificationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.modification_date
     *
     * @param modificationDate the value for user.modification_date
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setModificationDate(Integer modificationDate) {
        this.modificationDate = modificationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.modification_user
     *
     * @return the value of user.modification_user
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public Integer getModificationUser() {
        return modificationUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.modification_user
     *
     * @param modificationUser the value for user.modification_user
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setModificationUser(Integer modificationUser) {
        this.modificationUser = modificationUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sex
     *
     * @return the value of user.sex
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sex
     *
     * @param sex the value for user.sex
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.country
     *
     * @return the value of user.country
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.country
     *
     * @param country the value for user.country
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.province
     *
     * @return the value of user.province
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.province
     *
     * @param province the value for user.province
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.city
     *
     * @return the value of user.city
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.city
     *
     * @param city the value for user.city
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.county
     *
     * @return the value of user.county
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.county
     *
     * @param county the value for user.county
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setCounty(String county) {
        this.county = county == null ? null : county.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.mobile
     *
     * @return the value of user.mobile
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.mobile
     *
     * @param mobile the value for user.mobile
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.mobile_imei
     *
     * @return the value of user.mobile_imei
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getMobileImei() {
        return mobileImei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.mobile_imei
     *
     * @param mobileImei the value for user.mobile_imei
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setMobileImei(String mobileImei) {
        this.mobileImei = mobileImei == null ? null : mobileImei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.mobile_type
     *
     * @return the value of user.mobile_type
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getMobileType() {
        return mobileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.mobile_type
     *
     * @param mobileType the value for user.mobile_type
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setMobileType(String mobileType) {
        this.mobileType = mobileType == null ? null : mobileType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.usercol
     *
     * @return the value of user.usercol
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getUsercol() {
        return usercol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.usercol
     *
     * @param usercol the value for user.usercol
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setUsercol(String usercol) {
        this.usercol = usercol == null ? null : usercol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.card
     *
     * @return the value of user.card
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getCard() {
        return card;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.card
     *
     * @param card the value for user.card
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setCard(String card) {
        this.card = card == null ? null : card.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.utype
     *
     * @return the value of user.utype
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public Byte getUtype() {
        return utype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.utype
     *
     * @param utype the value for user.utype
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setUtype(Byte utype) {
        this.utype = utype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.hospital_id
     *
     * @return the value of user.hospital_id
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public Integer getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.hospital_id
     *
     * @param hospitalId the value for user.hospital_id
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setHospitalId(Integer hospitalId) {
        this.hospitalId = hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.hospital
     *
     * @return the value of user.hospital
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getHospital() {
        return hospital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.hospital
     *
     * @param hospital the value for user.hospital
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setHospital(String hospital) {
        this.hospital = hospital == null ? null : hospital.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.department_id
     *
     * @return the value of user.department_id
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.department_id
     *
     * @param departmentId the value for user.department_id
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.department
     *
     * @return the value of user.department
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.department
     *
     * @param department the value for user.department
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.title
     *
     * @return the value of user.title
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public Integer getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.title
     *
     * @param title the value for user.title
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setTitle(Integer title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.excel
     *
     * @return the value of user.excel
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getExcel() {
        return excel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.excel
     *
     * @param excel the value for user.excel
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setExcel(String excel) {
        this.excel = excel == null ? null : excel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.scount
     *
     * @return the value of user.scount
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public Byte getScount() {
        return scount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.scount
     *
     * @param scount the value for user.scount
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setScount(Byte scount) {
        this.scount = scount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sn_number
     *
     * @return the value of user.sn_number
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getSnNumber() {
        return snNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sn_number
     *
     * @param snNumber the value for user.sn_number
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setSnNumber(String snNumber) {
        this.snNumber = snNumber == null ? null : snNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sdrst
     *
     * @return the value of user.sdrst
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public Integer getSdrst() {
        return sdrst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sdrst
     *
     * @param sdrst the value for user.sdrst
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setSdrst(Integer sdrst) {
        this.sdrst = sdrst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sdserst
     *
     * @return the value of user.sdserst
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public Integer getSdserst() {
        return sdserst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sdserst
     *
     * @param sdserst the value for user.sdserst
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setSdserst(Integer sdserst) {
        this.sdserst = sdserst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.last_time
     *
     * @return the value of user.last_time
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public Integer getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.last_time
     *
     * @param lastTime the value for user.last_time
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setLastTime(Integer lastTime) {
        this.lastTime = lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.last_ip
     *
     * @return the value of user.last_ip
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getLastIp() {
        return lastIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.last_ip
     *
     * @param lastIp the value for user.last_ip
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setLastIp(String lastIp) {
        this.lastIp = lastIp == null ? null : lastIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.img_url
     *
     * @return the value of user.img_url
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.img_url
     *
     * @param imgUrl the value for user.img_url
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.telephone
     *
     * @return the value of user.telephone
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.telephone
     *
     * @param telephone the value for user.telephone
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.last_update_time
     *
     * @return the value of user.last_update_time
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public Integer getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.last_update_time
     *
     * @param lastUpdateTime the value for user.last_update_time
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setLastUpdateTime(Integer lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.last_blood_time
     *
     * @return the value of user.last_blood_time
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public Integer getLastBloodTime() {
        return lastBloodTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.last_blood_time
     *
     * @param lastBloodTime the value for user.last_blood_time
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setLastBloodTime(Integer lastBloodTime) {
        this.lastBloodTime = lastBloodTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.birthday
     *
     * @return the value of user.birthday
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public Integer getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.birthday
     *
     * @param birthday the value for user.birthday
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setBirthday(Integer birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.mobile1
     *
     * @return the value of user.mobile1
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getMobile1() {
        return mobile1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.mobile1
     *
     * @param mobile1 the value for user.mobile1
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setMobile1(String mobile1) {
        this.mobile1 = mobile1 == null ? null : mobile1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.mobile2
     *
     * @return the value of user.mobile2
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getMobile2() {
        return mobile2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.mobile2
     *
     * @param mobile2 the value for user.mobile2
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setMobile2(String mobile2) {
        this.mobile2 = mobile2 == null ? null : mobile2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.pic_url
     *
     * @return the value of user.pic_url
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.pic_url
     *
     * @param picUrl the value for user.pic_url
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.dept_pic_url
     *
     * @return the value of user.dept_pic_url
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getDeptPicUrl() {
        return deptPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.dept_pic_url
     *
     * @param deptPicUrl the value for user.dept_pic_url
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setDeptPicUrl(String deptPicUrl) {
        this.deptPicUrl = deptPicUrl == null ? null : deptPicUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_share_doctor
     *
     * @return the value of user.is_share_doctor
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public Byte getIsShareDoctor() {
        return isShareDoctor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_share_doctor
     *
     * @param isShareDoctor the value for user.is_share_doctor
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setIsShareDoctor(Byte isShareDoctor) {
        this.isShareDoctor = isShareDoctor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_share_community
     *
     * @return the value of user.is_share_community
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public Byte getIsShareCommunity() {
        return isShareCommunity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_share_community
     *
     * @param isShareCommunity the value for user.is_share_community
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setIsShareCommunity(Byte isShareCommunity) {
        this.isShareCommunity = isShareCommunity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.token
     *
     * @return the value of user.token
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.token
     *
     * @param token the value for user.token
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.im_status
     *
     * @return the value of user.im_status
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public Byte getImStatus() {
        return imStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.im_status
     *
     * @param imStatus the value for user.im_status
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setImStatus(Byte imStatus) {
        this.imStatus = imStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.im_password
     *
     * @return the value of user.im_password
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getImPassword() {
        return imPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.im_password
     *
     * @param imPassword the value for user.im_password
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setImPassword(String imPassword) {
        this.imPassword = imPassword == null ? null : imPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.salt
     *
     * @return the value of user.salt
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.salt
     *
     * @param salt the value for user.salt
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.union_id
     *
     * @return the value of user.union_id
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getUnionId() {
        return unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.union_id
     *
     * @param unionId the value for user.union_id
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setUnionId(String unionId) {
        this.unionId = unionId == null ? null : unionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.nurse
     *
     * @return the value of user.nurse
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public Integer getNurse() {
        return nurse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.nurse
     *
     * @param nurse the value for user.nurse
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setNurse(Integer nurse) {
        this.nurse = nurse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.card_no
     *
     * @return the value of user.card_no
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.card_no
     *
     * @param cardNo the value for user.card_no
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.card_name
     *
     * @return the value of user.card_name
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getCardName() {
        return cardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.card_name
     *
     * @param cardName the value for user.card_name
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setCardName(String cardName) {
        this.cardName = cardName == null ? null : cardName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.card_type
     *
     * @return the value of user.card_type
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public Byte getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.card_type
     *
     * @param cardType the value for user.card_type
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setCardType(Byte cardType) {
        this.cardType = cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.card_bank
     *
     * @return the value of user.card_bank
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getCardBank() {
        return cardBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.card_bank
     *
     * @param cardBank the value for user.card_bank
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setCardBank(String cardBank) {
        this.cardBank = cardBank == null ? null : cardBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.status
     *
     * @return the value of user.status
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.status
     *
     * @param status the value for user.status
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.code
     *
     * @return the value of user.code
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.code
     *
     * @param code the value for user.code
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.doctor_voice
     *
     * @return the value of user.doctor_voice
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getDoctorVoice() {
        return doctorVoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.doctor_voice
     *
     * @param doctorVoice the value for user.doctor_voice
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setDoctorVoice(String doctorVoice) {
        this.doctorVoice = doctorVoice == null ? null : doctorVoice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.channel
     *
     * @return the value of user.channel
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.channel
     *
     * @param channel the value for user.channel
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.license
     *
     * @return the value of user.license
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getLicense() {
        return license;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.license
     *
     * @param license the value for user.license
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setLicense(String license) {
        this.license = license == null ? null : license.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.wx_doctor
     *
     * @return the value of user.wx_doctor
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public Integer getWxDoctor() {
        return wxDoctor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.wx_doctor
     *
     * @param wxDoctor the value for user.wx_doctor
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setWxDoctor(Integer wxDoctor) {
        this.wxDoctor = wxDoctor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.wx_show
     *
     * @return the value of user.wx_show
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public Byte getWxShow() {
        return wxShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.wx_show
     *
     * @param wxShow the value for user.wx_show
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setWxShow(Byte wxShow) {
        this.wxShow = wxShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.expireAt
     *
     * @return the value of user.expireAt
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public Integer getExpireat() {
        return expireat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.expireAt
     *
     * @param expireat the value for user.expireAt
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setExpireat(Integer expireat) {
        this.expireat = expireat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.deviceUUID
     *
     * @return the value of user.deviceUUID
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getDeviceuuid() {
        return deviceuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.deviceUUID
     *
     * @param deviceuuid the value for user.deviceUUID
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setDeviceuuid(String deviceuuid) {
        this.deviceuuid = deviceuuid == null ? null : deviceuuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.os
     *
     * @return the value of user.os
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getOs() {
        return os;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.os
     *
     * @param os the value for user.os
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setOs(String os) {
        this.os = os == null ? null : os.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.osVer
     *
     * @return the value of user.osVer
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getOsver() {
        return osver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.osVer
     *
     * @param osver the value for user.osVer
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setOsver(String osver) {
        this.osver = osver == null ? null : osver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.appVer
     *
     * @return the value of user.appVer
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getAppver() {
        return appver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.appVer
     *
     * @param appver the value for user.appVer
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setAppver(String appver) {
        this.appver = appver == null ? null : appver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.card_mobile
     *
     * @return the value of user.card_mobile
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getCardMobile() {
        return cardMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.card_mobile
     *
     * @param cardMobile the value for user.card_mobile
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setCardMobile(String cardMobile) {
        this.cardMobile = cardMobile == null ? null : cardMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.pttype
     *
     * @return the value of user.pttype
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public Byte getPttype() {
        return pttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.pttype
     *
     * @param pttype the value for user.pttype
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setPttype(Byte pttype) {
        this.pttype = pttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.active
     *
     * @return the value of user.active
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public Byte getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.active
     *
     * @param active the value for user.active
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setActive(Byte active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.referer
     *
     * @return the value of user.referer
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getReferer() {
        return referer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.referer
     *
     * @param referer the value for user.referer
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setReferer(String referer) {
        this.referer = referer == null ? null : referer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.first_auth
     *
     * @return the value of user.first_auth
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public Byte getFirstAuth() {
        return firstAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.first_auth
     *
     * @param firstAuth the value for user.first_auth
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setFirstAuth(Byte firstAuth) {
        this.firstAuth = firstAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.trusteeshipStatus
     *
     * @return the value of user.trusteeshipStatus
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public Boolean getTrusteeshipstatus() {
        return trusteeshipstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.trusteeshipStatus
     *
     * @param trusteeshipstatus the value for user.trusteeshipStatus
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setTrusteeshipstatus(Boolean trusteeshipstatus) {
        this.trusteeshipstatus = trusteeshipstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.offline_channel_referer
     *
     * @return the value of user.offline_channel_referer
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getOfflineChannelReferer() {
        return offlineChannelReferer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.offline_channel_referer
     *
     * @param offlineChannelReferer the value for user.offline_channel_referer
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setOfflineChannelReferer(String offlineChannelReferer) {
        this.offlineChannelReferer = offlineChannelReferer == null ? null : offlineChannelReferer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.doctor_type
     *
     * @return the value of user.doctor_type
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public Byte getDoctorType() {
        return doctorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.doctor_type
     *
     * @param doctorType the value for user.doctor_type
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setDoctorType(Byte doctorType) {
        this.doctorType = doctorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.coin
     *
     * @return the value of user.coin
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public Integer getCoin() {
        return coin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.coin
     *
     * @param coin the value for user.coin
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setCoin(Integer coin) {
        this.coin = coin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.gmt_create
     *
     * @return the value of user.gmt_create
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.gmt_create
     *
     * @param gmtCreate the value for user.gmt_create
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.gmt_modify
     *
     * @return the value of user.gmt_modify
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.gmt_modify
     *
     * @param gmtModify the value for user.gmt_modify
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.wechat_union_id
     *
     * @return the value of user.wechat_union_id
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getWechatUnionId() {
        return wechatUnionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.wechat_union_id
     *
     * @param wechatUnionId the value for user.wechat_union_id
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setWechatUnionId(String wechatUnionId) {
        this.wechatUnionId = wechatUnionId == null ? null : wechatUnionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.subscribe_open_id
     *
     * @return the value of user.subscribe_open_id
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public String getSubscribeOpenId() {
        return subscribeOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.subscribe_open_id
     *
     * @param subscribeOpenId the value for user.subscribe_open_id
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setSubscribeOpenId(String subscribeOpenId) {
        this.subscribeOpenId = subscribeOpenId == null ? null : subscribeOpenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.subscribe_state
     *
     * @return the value of user.subscribe_state
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public Byte getSubscribeState() {
        return subscribeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.subscribe_state
     *
     * @param subscribeState the value for user.subscribe_state
     *
     * @mbggenerated Tue Aug 01 16:07:26 CST 2017
     */
    public void setSubscribeState(Byte subscribeState) {
        this.subscribeState = subscribeState;
    }
}